name: Update

on:
  workflow_dispatch:
  push:  # 添加此行以在push时触发
    paths-ignore:  # 避免无限循环
      - 'README.md'
      - '.github/ISSUE_TEMPLATE.md'
  label:
    types:
      - created # for test
  schedule:
      - cron: '30 16 * * 0,2' # 00:30 Beijing time every Monday to Friday
      
permissions:
  contents: write
  issues: write 

jobs:
  update_daily_papers:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Update papers
      run: |
        python main.py
    
    - name: Debug keywords
      run: |
        echo "Current keywords in main.py:"
        grep "keywords =" main.py
    
    - name: Commit and push changes
      uses: github-actions-x/commit@v2.9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'main'
        commit-message: '✏️ Update papers automatically.'
        force-add: 'true'
        files: README.md .github/ISSUE_TEMPLATE.md
        name: xydong
        email: gs.xydong24@gzu.edu.cn

    - name: Create an issue to notify
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
